name: keep_keyboard_popup_menu
description: A popup menu that will keep keyboard open.
version: 2.0.5
repository: https://github.com/PegasisForever/keep_keyboard_popup_menu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.0.0

dev_dependencies:


flutter:
